# Generated by Django 3.2.7 on 2021-09-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210904_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default='this is note'),
            preserve_default=False,
        ),
    ]
